# -*- coding: utf-8 -*-
"""labcycle2: 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ALqF4PX2-EGiO0S4sqjjIPYRgLn9GgjZ
"""

# 1.Suppose a newly born pair of rabbits, one male and one female, are 
#   put in a field. Rabbits can mate at the age of one month so that at the 
#   end of its second month, a female has produced another pair of 
#   rabbits. Suppose that our rabbits never die and that the female always 
#   produces one new pair every month from the second month.
#   Develop a program to show a table containing the number of pairs of 
#   rabbits in the first N months.

# function to get number of months from user
def input_mon():
  n= int(input("Enter the number of months : "))
  print(" ")
  return n

#function to generate a fibonacci series for getting number of pair rabbits
def calculate(n):
  month= []
  r_number= [0,1]
  for i in range (0,n):
    month.insert(i,i+1)
    r_number.insert(i+2,r_number[i+1]+r_number[i])
  r_number.remove(0)
  return month,r_number


# fuction to print number of pair of rabbits in input-out format
def print_result(n,m,r):
  print("+---------------------------------------+")
  print("| months |    No. of pair of rabbits    |")
  print("|--------|------------------------------|")
  for i in range (0,n):
    
    print("| ",m[i],"\t","|","\t\t",r[i],"\t\t|")
    if i!=n-1:
     print("|--------|------------------------------|")
  print("+---------------------------------------+")

# calling all functions
print("  Program to print the number of rabbits")
print(" ")
n=input_mon()
m,r=calculate(n)
print_result(n,m,r)