# -*- coding: utf-8 -*-
"""labcycle2: 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gXXIgwhNsjwO1dDMtjdzFtzkCtr2cG9b
"""

#2. Write a program to read a string containing numbers separated by a space and convert it as a list of integers. Perform the following 
#   Perform the following operations on it:
#     1. Rotate elements in a list by 'k' position to the right
#     2. Convert the list into a tuple using list comprehension
#     3. Remove all duplicates from the tuple and convert them into a list again.
#     4. Create another list by putting the results of the evaluation of the function 𝑓(𝑥) = 𝑥2 – 𝑥 with each element in the final list
#     5. After sorting them individually, merge the two lists to  create a single sorted list.

# function to input a string of numbers with space and convert string into a list of characters
def input_data():

  data= str(input("Enter a set of numbers separated by space              : "))
  array1=list(data)
  
  return array1


# function to convert characters to int and to store in a list 
def con_int(array1):
  
  n1=len(array1)
  array2=[]
  for i in range (0,n1,2):
    temp1=int(array1[i])
    array2.append(temp1)

  # to print  the list of numbers
  print(" ")
  print("List made of numbers                                   : ",array2)

  return array2

# function to rotate the list by k
def rotate(array2):

  # creating a copy of list
  n2=len(array2)
  array3=[x for x in array2]
  
  n3=len(array3)
  print(" ")
  k=int(input("Enter the value of k to rotate the list of numbers     : "))
  
  l=0
  while l!=k:
    for i in range (0,n2-1,):
      array2[i+1]=array3[i]
    array2[0]=array3[n3-1]
    array3=array3=[x for x in array2]
    l=l+1

  # to print the rotated list of numbers
  print(" ")
  print("List after rotation                                    : ",array2) 
  
# function to convert the list into a tuple
def con_tuple(array2):
  
  t1=tuple([x for x in array2])
  #to print the tuple made by list comprehension
  print(" ")
  print("The tuple made of list comprehension                   : ",t1)
  
  return t1
 
# function to remove duplicates and convert the tuple into a list
def con_list(t1):

  #removing duplicates 
  s1=set(t1)
  #converting to list 
  array5=list(s1)
  #to check new list
  print(" ") 
  print("The list made after removing duplicates                : ",array5)
  
  return array5

# function to make list with output 𝑓(𝑥) = 𝑥2 – 𝑥
def func(array5): 
  #list with out put from the function 𝑓(𝑥) = 𝑥2 – 𝑥
  array6=[x**2-x for x in array5]
  #to check new list 
  print(" ")
  print("The list made of output of the function 𝑓(𝑥) = 𝑥2 – 𝑥  : ",array6)

  return array6

def final(array5,array6):
  #sorting 2 list
  array5.sort()
  array6.sort()
  array7= array5 + array6
  array7.sort()

  #to check final list
  print(" ")
  print("The final list made of merging two lists               : ",array7)


print("                 Operations on string of numbers ")
print("                --------------------------------- ")
l1=con_int(input_data())
rotate(l1)
t1=con_tuple(l1)
l2=con_list(t1)
l3=func(l2)
final(l2,l3)