# -*- coding: utf-8 -*-
"""labcycle2: 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kNLORB0mqqYphdtsNlxjKJrM8gZeTJeU
"""

# 5.Write a program to create a parent class, 3DShapes, with methods 
#   printVolume() and printArea(), which prints the Volume and Area,
#   respectively. Create classes Cylinder and Sphere by inheriting
#   3DShapes class. Using these child classes, calculate and print the
#   volume and area of a cylinder and sphere.

#creating base class
class Shapes:

  #protected member functions
  _Volume= None
  _Area= None

#function to print area and volume
  def printVolume(self):
    print("Volume : ",self._Volume)
  def printArea(self):
    print("Area   : ",self._Area)

#creating derived class
class Cylinder(Shapes):

  __radius=None
  __height=None

  def __init__(self,r,h):
    self.__radius=r
    self.__height=h

  def calcVolume(self):
    self._Volume= 3.14*self.__radius*self.__radius*self.__height

  def calcArea(self):
    self._Area= 6.28*self.__radius*(self.__height + self.__radius)

#creating derived class
class Sphere(Shapes):

  __radius=None
  def __init__(self,r):
      self.__radius=r

  def inputData(self):
    r=float(input("Enter the radius of the sphere : "))
    self.__radius=r
    
  def calcVolume(self):
    self._Volume= 4.1867*self.__radius*self.__radius*self.__radius

  def calcArea(self):
    self._Area= 12.56*self.__radius*self.__radius
    
# function to get input
def input_det():

  r1=float(input("Enter the radius of the cylinder : "))
  h=float(input("Enter the height of the cylinder : "))
  print(" ")
  r2=float(input("Enter the radius of the sphere : "))
  print(" ")

  return r1,h,r2

r1,h,r2=input_det()
# creating objects and calling functions of class cylinder
cylinder1= Cylinder(r1,h)
cylinder1.calcVolume()
cylinder1.calcArea()
print("  Cylinder")
cylinder1.printArea()
cylinder1.printVolume()
print(" ")

# creating objects and calling functions
sphere1= Sphere(r2)
sphere1.calcVolume()
sphere1.calcArea()
print("    Sphere")
sphere1.printArea()
sphere1.printVolume()