# -*- coding: utf-8 -*-
"""labcycle1: 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YxkwclkLXfvFpaonwVt_Y9HfMGTp1i4v
"""

# 1. Develop a program to read a four-digit number and find its
#   a. Sum of digits
#   b. Reverse
#   c. Difference between the product of digits at the odd position
#      and the product of digits at the even position

# function to get input from user
def get_input():

  num1 = int(input("Enter a four digit number, Number:-1 : "))

  return num1

# function to calculate results
def calculate(x):

  units=x%10                                # to get units digit
  x=x//10
  tens=x%10                                 # to get tens digit
  x=x//10
  hunds=x%10                                # to get hundreds digit
  x=x//10
  thous=x%10                                # to get thousands digits

 
  s=units+tens+hunds+thous                  # sum of digits
  r=units*1000+tens*100+hunds*10+thous      # reverse of number
  d=thous*tens-hunds*units                  # special sum from sub question c

  return s,r,d

#function to print results
def print_result(a,b,c):

  print("Sum of digits of Number:-1           : ",a)      
  print("Reverse of Number:-1                 : ",b)             
  print("Difference with digits of Number:-1  : ",c)       

#calling functions
sum,rev,dif=calculate(get_input())
print(" ")
print_result(sum,rev,dif)