# -*- coding: utf-8 -*-
"""labcycle1: 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V5Oxln-G0FpGxW7WF_69dEAd229ZGmIV
"""

# Develop a program to read the three sides of two triangles and
# calculate the area of both. Define a function to read the three sides
# and call it. Also, define a function to calculate the area. Print the total
# area enclosed by both triangles and each triangle's contribution (%)
# towards it

# function to input sides of the triangle 
def input_sides():

  print(" ")
  a= float(input("Enter side 1 : "))
  b= float(input("Enter side 2 : "))
  c= float(input("Enter side 3 : "))
  print(" ")

  return a,b,c

# function to calculate area
def calc_area(a,b,c):

  s= (a+b+c)/2
  ar= (s*(s-a)*(s-b)*(s-c))**0.5

  return ar

# calling fuction to input sides and calculate area
print("Triangle 1: ")
a1,b1,c1=input_sides()
ar1=calc_area(a1,b1,c1)

print("Triangle 2: ")
a2,b2,c2=input_sides()
ar2=calc_area(a2,b2,c2)

# printing total area and contribution of each triangle
print("                Total Area = ",ar1+ar2)
print("Contribution of Triangle 1 = ",ar1/(ar1+ar2)*100,"%")
print("Contribution of Triangle 2 = ",ar2/(ar1+ar2)*100,"%")