# -*- coding: utf-8 -*-
"""labcycle1: 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zL0xfaNDvYvb9PzDSGSO4Pi3xy5qYzt1
"""

# Develop a program to perform the following task:
# a. Define a function to check whether a number is happy or not.
# b. Define a function to print all happy numbers within a range.
# c. Define a function to print first N happy numbers.num=int(input("enter any whole number: "))
def check(num):#fuction to check if it is happy number
  sum=0# sum for adding the square of digits
  is_happy= False#to return true if it is a happy number
  for i in range(100):# for loop for testing if it is haapy 
   while(num>0):# while loop for a single iteration where number becomes 0 and sum becomes sum of square of digits
    rem=num%10
    sum=sum+rem**2
    num=num//10
   if(sum==1):#checking is sum = 1
    is_happy=True#changing is happy to true if sum =1
    break#breaking from the loop
   else:
    num=sum#if not happy number repeat by making sum equal to number and sum equal to zero
    sum=0
  return is_happy#fuction to print a happy number with in a range
     
if(check(num)==True):
  print("it is a happy number")
else:
   print("it is not a happy number")

def ran():
  up=int(input("enter the upper limit: ")) #upper limit
  dn=int(input("enter the lower limit: ")) #lower limit
  for i in range(dn,up):
   if(check(i)==True):
     print(i)#printing happy numbers within the range
ran()
def n_item():#function to print n happy number
  n= int(input("enter the value of n to print first n happy numbers: "))
  count=0
  i=0
  while(count<n): # loop to check and print first n happy number
      i=i+1
      if(check(i)==True):
        print(i)
        count=count+1
  
n_item()