# -*- coding: utf-8 -*-
"""labcycle1: 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YL-ecZ-WuFyFKkpf-uX4phs4DeY2AW1H
"""

# 5. Develop a program to read a string and perform the following operations:
#    • Print all possible substrings.
#    • Print all possible substrings of length K.
#    • Print all possible substrings of length K with N distinct characters.
#    • Print substring(s) of length maximum length with N distinct characters.
#    • Print all palindrome substrings.

# function to get a string from user
def get_string():

  st=str(input("Enter any string : "))          # taking a string as an input
  print(" ") 

  return st 

# function to print all possible substrings
def sub_str1(st):
                     
  for i in range(0,len(st)+1):
    for j in range(i+1,len(st)+1):
      s=st[i:j]
      print(s)

# function to print all substrings of a specific length
def sub_str2(st):
  
  k= int(input("Enter the length of substring : "))
  print(" ")
  m=0 
  for i in range(0,len(st)+1):
    for j in range(i+1,len(st)+1):
      s=st[i:j]
      if(len(s)==k):
       print(s)
       m=m+1
  if(m==0):
    print("No substring with length ",k)


# function to print all substings of specific distinct character and length
def sub_str3(st):

  m=0
  k= int(input("Enter the length of substring           : "))
  n= int(input("Enter the number of distinct characters : "))
  print(" ") 
  for i in range(0,len(st)+1):
    for j in range(i+1,len(st)+1):
      s=st[i:j]
      if(len(s)==k and len(set(s))==n): 
       print(s)
       m=m+1
  if(m==0):
    print("No substring with length ",k," and ",n," distinct characters")

# fuction to print longest substring with specific distinct charcters
def sub_str4(st):

  l=[]
  m=0
  n= int(input("Enter the number of distinct characters : "))
  print(" ") 
  for i in range(0,len(st)+1):
    for j in range(i+1,len(st)+1):
      s=st[i:j]
      if(len(set(s))==n):
       l.append(s)
  m=len(max(l,key=len))
  for i in l:
    if(len(i)==m):
      print(i)
  if(m==0):
    print("No substring with ",n," distinct characters")

# to check if palindrome or not
def sub_str5(st):

  m=0
  for i in range(0,len(st)+1):
    for j in range(i+1,len(st)+1):
      s=st[i:j]
      temp=s[::-1]
      if(s==temp):
        print(s)
        m=m+1
  if(m==0):
    print("No substring which is a palindrome")
  

# calling all fuctions
s=get_string()
print("          All Substrings")  
print("         ----------------")        
sub_str1(s)
print(" ")   

print(" All substrings with specific length")
print("------------------------------------- ")  
sub_str2(s)
print(" ") 

print(" All substrings with specific length and distinct terms")
print("-------------------------------------------------------- ")  
sub_str3(s)
print(" ")  

print(" All substrings with specific distinct terms and maximum length")
print("---------------------------------------------------------------- ")  
sub_str4(s)
print(" ")  

print(" All the palindromes")
print("--------------------- ")  
sub_str5(s)